### ISSUE TITLE
[BUG] - Can't rename Options

### ISSUE THREAD

**Issue by Ikabodo** [misterpotts/fabricate#118]
## Describe the bug
If you try to rename an option in the Requirement section it resets almost immediately.

**Comment by misterpotts** [comment]
What do you mean when you say "resets" - it removes your changes?

**Comment by Ikabodo** [comment]
![image](https://user-images.githubusercontent.com/7766890/227219290-17ca3fcc-7ace-47ea-ba0c-72e3c031dc12.png)

**Comment by Ikabodo** [comment]
Interestingly it works for Results, not not Requirements.
