### ISSUE TITLE
Update to 0.8.8?

### ISSUE THREAD

**Issue by CalabC** [misterpotts/fabricate#46]
Title.

**Comment by misterpotts** [comment]
I'd love to.

However, as I mentioned on the League discord:
1. The rewrite is still not quite finished, and needs to be pushed over the line before I can change how the inventory interacts with the Actor
2. I'm having some personal health issues that limit the amount of time I can spend at the computer at the moment and I do it for a living already. If you'd like to contribute I'd be happy to help you get started

**Comment by CalabC** [comment]
I didn't know, sorry about your health and I do hope you get better!
