### ISSUE TITLE
"Crafting system" button becomes non-interactable

### ISSUE THREAD

**Issue by miscalculations** [misterpotts/fabricate#74]
While adding a bunch of my recipes to the crafting system, at one point I had re-made an item that was already placed into the components section. I deleted the old item and made a new one. When trying to open my system under the default "alchemist's supplies" button, it no longer does anything.

I reproduced this by creating a new crafting system, adding an item from a compendium, then deleting the item from my compendium. I can no longer open the crafting system to edit it or remove the now missing item. The only action that seems to work is duplicating or deleting the system. Deleting it works, trying to open the now duplicated system also does not work as the first one.

**Comment by misterpotts** [comment]
Thanks for the report! 🐛 

Ah okay, I know why this happens. Fabricate loads up and looks for the item reference, but it's not there.

I can subscribe to lifecycle hooks to delete the item from the crafting systems it is included in, or provide a prompt to users when it loads to delete the item from systems, and even load up the broken systems and make them "fixable" by letting you drop in a replacement item to fix the broken link, or to just delete them.

For now I think I'll provide a prompt to users when it loads to delete the item from systems. That's the fastest way to fix the issue.

For future bug reports, there's a template you can use (under [New Issue](https://github.com/misterpotts/fabricate/issues/new/choose) you can select [Bug Report](https://github.com/misterpotts/fabricate/issues/new?assignees=&labels=bug&template=bug_report.md&title=)) that provides more detail to make diagnosing the issue easier for me. 

Thanks in advance :)
