### ISSUE TITLE
[BUG] The loading modal gets stuck over the interface when you drag the wrong kind of item onto it.

### ISSUE THREAD

**Issue by Ikabodo** [misterpotts/fabricate#90]
## Describe the bug
If you drag the wrong kind of item onto the interface, a loading modal shows up. It should dissapear.

## To Reproduce
Drag a non allowed item onto the interface.

## Expected behavior
A warning that it is the wrong kind of item. No stuck loading.

## Screenshots
![image](https://user-images.githubusercontent.com/7766890/225148872-4c2fd0f0-663d-4694-b491-f0a9a6607433.png)

## Version information
- Fabricate version: [e.g. 0.8.1

**Comment by misterpotts** [comment]
I will have to look into whether this happens in all drop zones (incl. essences and recipes) too.

**Comment by Ikabodo** [comment]
It does. It only happens if you drop it on one of the drop boxes though. The ones with a + sign.

**Comment by misterpotts** [comment]
Thanks for checking!

**Comment by misterpotts** [comment]
Fixed in `0.8.2` (Pre-Release)
