### ISSUE TITLE
[BUG] - Trouble renaming results

### ISSUE THREAD

**Issue by Ikabodo** [misterpotts/fabricate#91]
## Describe the bug
When you create more than one optional result in a recipe, wierd things happen. Especially if you try to delete text. It is editing the wrong option.

## To Reproduce
Create a second or more Result option. Rename or delete text in the name field. Watch.

## Expected behavior
Like it does in Requirements.

## Version information
- Fabricate version: [e.g. 0.8.1]

**Comment by misterpotts** [comment]
This is the strangest bug so far! No idea what will be going on here until I get into it.

**Comment by misterpotts** [comment]
Fixed in `0.8.2` (Pre-Release)
